# -*- coding: utf-8 -*-
"""Calculadora teste.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11uM-iKPZxI4nGFQVEN6dtGZDyEsgToIC
"""

nome = input("Digite seu nome: ")

print(f"Olá, {nome}!")

num1 = float(input(f"{nome}, digite por gentileza seu primeiro número: "))

num2 = float(input(f"{nome}, digite por gentileza seu segundo número: "))

operacao = input("Agora escolha a operação matemática desejada(+, -, * ou /): ")

if operacao == "+":
  print(num1 + num2)
elif operacao == "-":
  print(num1 - num2)
elif operacao == "*":
  print(num1 * num2)
elif operacao == "/":
  print(num1 / num2)
else:
  print("Operação inválida")

